name: Deploy Docs

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件（如果您的主分支是 master，请更改）
  workflow_dispatch: # 允许手动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # 必须要有写入权限才能推送到 gh-pages 分支
      pages: write   # 部署到 Pages 需要此权限
      id-token: write # 需要此权限来使用 OIDC 认证

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 推荐使用官方的 actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 安装 MkDocs 和 Material 主题以及您的所有插件
      - name: Install dependencies
        run: pip install mkdocs-material

      # 如果您在 requirements.txt 中列出了其他依赖，请使用：
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      
      # 构建网站并推送到 gh-pages 分支
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
